brew install ack
brew install bash-completion
brew install cairo
brew install colordiff
brew install fontconfig
brew install freetype
brew install fribidi
brew install fzf
brew install gdk-pixbuf
brew install gettext
brew install glib
brew install graphite2
brew install harfbuzz
brew install icu4c
brew install jpeg
brew install libcroco
brew install libffi
brew install libidn2
brew install libpng
brew install librsvg
brew install libtiff
brew install libunistring
brew install links
brew install node
brew install nvm
brew install openssl
brew install pango
brew install pcre
brew install pixman
brew install the_silver_searcher
brew install wget
brew install xz
