code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension austenc.laravel-blade-spacer
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.path-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension cobeia.airbnb-react-snippets
code --install-extension codingyu.laravel-goto-view
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension emilast.LogFileHighlighter
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felipe-mendes.slack-theme
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension fterrag.vscode-php-cs-fixer
code --install-extension Gruntfuggly.global-config
code --install-extension ikappas.phpcs
code --install-extension JerryHong.autofilename
code --install-extension junstyle.php-cs-fixer
code --install-extension joelday.docthis
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension lihui.vs-color-picker
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension neilbrayfield.php-docblocker
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension octref.vetur
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension pajdziu.trailingwhitespacehighlighter
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension robertohuertasm.vscode-icons
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension ryannaddy.laravel-artisan
code --install-extension ryu1kn.partial-diff
code --install-extension ryuta46.multi-command
code --install-extension shardulm94.trailing-spaces
code --install-extension SirTori.indenticator
code --install-extension sleistner.vscode-fileutils
code --install-extension slevesque.vscode-multiclip
code --install-extension stef-k.laravel-goto-controller
code --install-extension stevencl.addDocComments
code --install-extension techer.open-in-browser
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension whizkydee.material-palenight-theme
code --install-extension whtouche.vscode-js-console-utils
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension yatki.vscode-surround
code --install-extension zignd.html-css-class-completion
