code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension austenc.laravel-blade-spacer
code --install-extension christian-kohler.path-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension cobeia.airbnb-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension emilast.LogFileHighlighter
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felipe-mendes.slack-theme
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension fterrag.vscode-php-cs-fixer
code --install-extension Gruntfuggly.global-config
code --install-extension ikappas.phpcs
code --install-extension JerryHong.autofilename
code --install-extension joelday.docthis
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension lihui.vs-color-picker
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension neilbrayfield.php-docblocker
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension pajdziu.trailingwhitespacehighlighter
code --install-extension pnp.polacode
code --install-extension robertohuertasm.vscode-icons
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension ryu1kn.partial-diff
code --install-extension ryuta46.multi-command
code --install-extension SirTori.indenticator
code --install-extension sleistner.vscode-fileutils
code --install-extension slevesque.vscode-multiclip
code --install-extension stevencl.addDocComments
code --install-extension techer.open-in-browser
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension whizkydee.material-palenight-theme
code --install-extension whtouche.vscode-js-console-utils
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension yatki.vscode-surround
